version: '3.8'

services:
  nihongo:
    image: nihongo-runtime  # 你用 Dockerfile.dev 构建的镜像
    container_name: nihongo
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app                    # 挂载当前目录代码到容器中
    env_file:
      - .env.local                 # 加载本地配置
    command: >
      sh -c "npm install &&
             npm run init-db &&
             npm run dev"