version: '3.8'

services:
  nihongo:
    image: nihongo-runtime
    container_name: nihongo
    ports:
      - "3000:3000"
    volumes:
      - ./config/.env.local:/app/.env.local:ro
    working_dir: /app
    command: npm run start